hosts:
- AskNowEmail:
  - title: smtp5.asknow.com
    sshparams: bradleyd@192.168.70.24
    type: host
    geometry: ""
  - title: smtp4.asknow.com
    sshparams: bradleyd@192.168.70.32
    type: host
    geometry: ""
  - title: smtp3.asknow.com
    sshparams: bradleyd@192.168.70.31
    type: host
    geometry: ""
  - title: smtp2.asknow.com
    sshparams: bradleyd@192.168.70.33
    type: host
    geometry: ""
  - title: smtp01x01
    sshparams: pair@smtp01x01
    type: host
    geometry: ""
  - title: smtp01x02
    sshparams: pair@smtp01x02
    type: host
    geometry: ""
- FST_MAIL:
  - title: mail--eglobalspecialties.com
    sshparams: pair@192.168.60.5
    type: host
    geometry: ""
  - title: mailgw--eglobalspecialties.com
    sshparams: pair@192.168.60.11
    type: host
    geometry: ""
- Oracle:
  - title: filmore
    sshparams: bradleyd@filmore
    type: host
    geometry: ""
  - title: choks
    sshparams: bradleyd@choks
    type: host
    geometry: ""
  - title: bebe64
    sshparams: bradleyd@bebe64
    type: host
    geometry: ""
  - title: sparky64
    sshparams: bradleyd@sparky64
    type: host
    geometry: ""
  - title: wendy64
    sshparams: bradleyd@wendy64
    type: host
    geometry: ""
  - title: sparky
    sshparams: bradleyd@sparky
    type: host
    geometry: ""
  - title: clyde
    sshparams: bradleyd@clyde
    type: host
    geometry: ""
  - title: merch-db
    sshparams: bradleyd@merch-db
    type: host
    geometry: ""
  - title: fluffy
    sshparams: bradleyd@fluffy
    type: host
    geometry: ""
  - title: orastage
    sshparams: bradleyd@orastage
    type: host
    geometry: ""
- FST_IVR:
  - title: pfvi01
    sshparams: -t pair@pfvi01 screen -x
    type: host
    geometry: ""
  - title: pfvi02
    sshparams: -t pair@pfvi02 screen -x
    type: host
    geometry: ""
  - title: pfvi03
    sshparams: -t pair@pfvi03 screen -x
    type: host
    geometry: ""
  - title: pfvi04
    sshparams: -t pair@pfvi04 screen -x
    type: host
    geometry: ""
  - title: pfvi05
    sshparams: -t pair@pfvi05 screen -x
    type: host
    geometry: ""
  - title: pfvi06
    sshparams: -t pair@pfvi06 screen -x
    type: host
    geometry: ""
  - title: pfvi08
    sshparams: -t pair@pfvi08 screen -x
    type: host
    geometry: ""
  - title: pfvi09
    sshparams: -t pair@pfvi09 screen -x
    type: host
    geometry: ""
  - title: pfvi10
    sshparams: -t pair@pfvi10 screen -x
    type: host
    geometry: ""
  - title: pfvi11
    sshparams: -t pair@pfvi11 screen -x
    type: host
    geometry: ""

