# Example host file.
# # Uncomment example below to add hosts.  Replace all text between brackets
#
# # NOTE: must begin with hosts:
hosts: #do not change name without changing source code
#- [Host_Category]:  <-- change to dns, smtp, etc..
# - title: [title or hostname]
# #could use other options for ssh here. see man page. For example -t user@host screen -x
# sshparams: [user@host]
# type: [host type; smtp, dns, web, etc...]
# geometry: "" <--keep nil; future use
