# All these values can be changed to meet your requirements
# This Log entry is for use by the Log class
log:
 log_file: app_indicator_ssh.log              # set log file name
 log_level: info                              # set the log level
 name: ais                                    # set name of log object

# smtp options for logging. Please change values below to match your environment
smtp:
  server: smtp.example.com
  port: 25
  domain: example.com
  from_address: ais@example.com
  to_address: you@example.com

